import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kristian Saomi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-blue-700">
        <h1>Hello</h1>
        <h2>hello</h2>
        </section>
      </main>
    </div>
  )
}
